### ISSUE TITLE
consistency in style/bold face

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical-cybertools.github.io#11]
In http://radical-cybertools.github.io/entk/index.html

We should: 

- remove boldface from the opening paragraph/definition of EnTK 
- spacing between items under "Features" should be less.
- Spacing/font consistent with http://radical-cybertools.github.io/radical-pilot/index.html

**Comment by iparask** [comment]
Resolved in commit d67267dad604257b53532b5e240779cb29aedd16
