### ISSUE TITLE
error when executing "getting started" RP 

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical-cybertools.github.io#24]
(RADICALPilot)RandomDisorder:radical-cybertools shantenu$ python 00_getting_started.py

================================================================================
 Getting Started (RP version 0.41)                                              
================================================================================

new session: [rp.session.RandomDisorder.local.shantenu.016999.0002]            \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read configcaught Exception: [Errno 2] No such file or directory: '/Users/shantenu/radical-cybertools/config.json'

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.RandomDisorder.local.shantenu.016999.0002           \
session lifetime: 0.1s                                                        ok
Traceback (most recent call last):
  File "00_getting_started.py", line 48, in <module>
    config = ru.read_json('%s/config.json' % os.path.dirname(os.path.abspath(__file__)))
  File "/Users/shantenu/radical-cybertools/RADICALPilot/lib/python2.7/site-packages/radical/utils/read_json.py", line 26, in read_json
    with open (filename) as f:
IOError: [Errno 2] No such file or directory: '/Users/shantenu/radical-cybertools/config.json'

**Comment by iparask** [comment]
Ooooops!

**Comment by iparask** [comment]
Added instructions to download the config file

**Comment by iparask** [comment]
Change wget to cd to the virtualenv

**Comment by iparask** [comment]
Done
