### ISSUE TITLE
error when executing "getting started" EnTK

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical-cybertools.github.io#25]
(myenv)RandomDisorder:~ shantenu$ RADICAL_ENTK_VERBOSE=REPORT python pipeline_of_ensembles.py
Traceback (most recent call last):
  File "pipeline_of_ensembles.py", line 59, in <module>
    with open('%s/config.json'%os.path.dirname(os.path.abspath(__file__))) as data_file:    
IOError: [Errno 2] No such file or directory: '/Users/shantenu/config.json'

**Comment by iparask** [comment]
Added instructions to download the config file

**Comment by iparask** [comment]
Change wget to cd to the virtualenv

**Comment by iparask** [comment]
Done
