### ISSUE TITLE
EnTK - getting started error.

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical-cybertools.github.io#28]
When on: http://radical-cybertools.github.io/entk/quick_start.html

(myenv)RandomDisorder:~ shantenu$ RADICAL_ENTK_VERBOSE=REPORT python pipeline_of_ensembles.py
Traceback (most recent call last):
  File "pipeline_of_ensembles.py", line 59, in <module>
    with open('%s/config.json'%os.path.dirname(os.path.abspath(__file__))) as data_file:    
IOError: [Errno 2] No such file or directory: '/Users/shantenu/config.json'

**Comment by vivek-bala** [comment]
Just change to the VE directory.

**Comment by iparask** [comment]
Done
