### ISSUE TITLE
entk & rp -- set cores=2 for localhost

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical-cybertools.github.io#32]
add "cores" as another key to the config JSON file. set it to 2 for local and larger numbers for stampede, comet, etc.

**Comment by iparask** [comment]
I already corrected the webpage to show 2 cores on localhost

**Comment by andre-merzky** [comment]
Implemented for RP.  However, I won't be able to update the user guide consistently, since that uses screenshots which I won't be able to complete in time with the new examples.  But I think that this is acceptable, the changes are very minor.

**Comment by iparask** [comment]
I think this is done!
