### ISSUE TITLE
Refinements on RADICAL-Cybertools landing page.

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical-cybertools.github.io#33]
We currently have: 

"It currently consists of three components: RADICAL-Pilot: a scalable and flexible Pilot-Job system that provides flexible application-level resource management capabilities; RADICAL-SAGA: a lightweight interface that provides a standards-based interoperability across a range of computing systems, and Ensemble-Toolkit that simplifies the ability to implement ensemble-based appliations."

I propose:
(i) we be consistent in the order in which we introduce the tools (Here RP->SAGA->EnTK). Lower in the page it is SAGA->RP-EnTK.
(ii) consistency between Ensemble Toolkit vs Ensemble-Toolkit on this page!

Thus:

"It currently consists of three components: RADICAL-SAGA: a standards-based interface that provides basic interoperability across a range of computing middleware; RADICAL-Pilot: a scalable and flexible Pilot-Job system that provides flexible application-level resource management capabilities, and Ensemble Toolkit that simplifies the ability to implement  ensemble-based applications."

**Comment by vivek-bala** [comment]
Agree. Should be SAGA->RP->EnTK. Is this change committed (or should I do it) ?
