### ISSUE TITLE
links in Radical-Saga don't work.

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical-cybertools.github.io#38]
http://radical-cybertools.github.io/saga-python/
in Supported Middleware section links are not working

**Comment by marksantcroos** [comment]
Ironically https://github.com/radical-cybertools/saga-python/issues/359 was closed as outdated today.

**Comment by iparask** [comment]
There are not any adaptor list in the documentation. So I am commenting the hyperlinks

**Comment by iparask** [comment]
Fixed, it will need some time until the page is rendered again

**Comment by andre-merzky** [comment]
> Ironically radical-cybertools/saga-python#359 was closed as outdated today

Ahaha :)  I saw that the explicit adaptor documentation parts in readthedocs where disabled, so those links are not broken anymore (but simply gone).  Wasn't aware that the adaptor docs are linked on the web page (yes, I see now that the ticket comment says just that...). Apologies!
